# Generated by Django 3.1.7 on 2021-09-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauron_ecommerce', '0003_auto_20210907_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
