# Generated by Django 3.1.7 on 2021-09-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauron_ecommerce', '0005_auto_20210907_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ville',
            field=models.CharField(default='Paris', max_length=50),
        ),
    ]
